### ISSUE TITLE
Add nested forms without hitting "Update Books"

### ISSUE THREAD

**Issue by julialoh** [philgyford/django-nested-inline-formsets-example#5]
Hello! Is it possible to add more books or more book images without having to click update books? I can't add any book images at all (besides the one that's generated with each book formset) and can only add a book one at a time.

**Comment by philgyford** [comment]
In `forms.py` look for the lines like:

```python
            extra=1,
```

These control how many `BookImage`s or `Books` to display in the form. They're both set at 1 but you can increase them.
